# Generated by Django 3.0.2 on 2020-01-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='about',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='author',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
